### PR TITLE
restore screen states

### PR DESCRIPTION
**Pull request by berkanturkali**

### CODE REVIEW

**Comment by tfaki** [comment]
@berkanturkali hi berkan, can you remove the comments in the viewmodels and can you refactor parameters name in the screens (like nowPlayingItems, upcomingItems etc.)

**Comment by berkanturkali** [comment]
@tfaki Hey Talha, do you mean by "remove the comments in the viewmodels", deleting the functions that I've commented out entirely, or reverting back them to how they already were previously?

**Comment by tfaki** [comment]
@berkanturkali if you're sure it's better you can delete the old one

**Comment by berkanturkali** [comment]
@tfaki Okay I've updated the code as you have said.

**Comment by tfaki** [comment]
@berkanturkali looks good. Nice job 🚀

**Pull request merged**
